# Generated by Django 4.2.13 on 2025-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_item', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=300)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'FAQS',
                'ordering': ['faq_item'],
            },
        ),
    ]
