# Generated by Django 4.2.13 on 2024-09-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawfaq',
            options={'ordering': ['number'], 'verbose_name_plural': 'FAQS'},
        ),
        migrations.AddField(
            model_name='lawfaq',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
