# Generated by Django 4.2.13 on 2025-12-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['item']},
        ),
    ]
