# Generated by Django 4.2.13 on 2024-08-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_product_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-item']},
        ),
    ]
