# Generated by Django 4.2.13 on 2024-09-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_options_product_has_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_options',
        ),
    ]
