# Generated by Django 4.2.13 on 2024-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.IntegerField(null=True),
        ),
    ]
