# Generated by Django 4.2.13 on 2024-09-11 06:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='dfy0one9z', max_length=255, verbose_name='image'),
        ),
    ]
