# Generated by Django 4.2.13 on 2024-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cooperation_partner',
            field=models.CharField(default='Svedea', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='has_cooperation_partner',
            field=models.BooleanField(default=False),
        ),
    ]
