# Generated by Django 4.2.13 on 2024-09-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_product_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='description_order',
        ),
    ]
