# Generated by Django 4.2.13 on 2025-08-04 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
