# Generated by Django 4.2.13 on 2024-09-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requesthelp',
            options={'verbose_name_plural': 'Requests'},
        ),
    ]
