# Generated by Django 4.2.13 on 2024-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_requesthelp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
