# Generated by Django 4.2.13 on 2024-09-09 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_requesthelp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthelp',
            name='message',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
